/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */
import type { DefaultAccountSeed } from '../types';

/**
 * Australian SME default Chart of Accounts spine — FY2026.
 * 121 rows; codes per Xero AU / MYOB AU convention (1xxx Asset, 2xxx Liability,
 * 3xxx Equity, 4xxx Revenue, 5xxx COGS, 6xxx Expense).
 *
 * Source: .planning/phases/04-bookkeeping-core/04-RESEARCH.md
 * "Default Australian SME Chart of Accounts (~120 rows, FY2026)" — verbatim.
 *
 * Structure:
 *   Assets (22) + Liabilities (18) + Equity (10) + Revenue (15)
 *   + COGS (6) + Operating Expenses (50) = 121 rows
 *
 * Header rows have parentCode: null and N-T GST; they appear as subtotals on TB.
 * Tax-label columns are FY2026 label IDs from src/lib/tax/labels/fy2026.ts
 * (NAT 2541/2543 individual, NAT 0656 company, NAT 0660 trust, NAT 0659 partnership).
 */
export const FY2026_BASE_SPINE: DefaultAccountSeed[] = [
  // ── Assets (22 rows) ────────────────────────────────────────────────────
  { code: '1000', name: 'Current Assets',                  type: 'Asset',     parentCode: null,   gstCode: 'N-T' },
  { code: '1010', name: 'Cash on Hand',                    type: 'Asset',     parentCode: '1000', gstCode: 'N-T' },
  { code: '1020', name: 'Business Bank Account',           type: 'Asset',     parentCode: '1000', gstCode: 'N-T' },
  { code: '1030', name: 'Business Savings Account',        type: 'Asset',     parentCode: '1000', gstCode: 'N-T' },
  { code: '1040', name: 'Petty Cash',                      type: 'Asset',     parentCode: '1000', gstCode: 'N-T' },
  { code: '1100', name: 'Accounts Receivable',             type: 'Asset',     parentCode: '1000', gstCode: 'N-T', notes: 'Trade Debtors control' },
  { code: '1110', name: 'Provision for Doubtful Debts',    type: 'Asset',     parentCode: '1000', gstCode: 'N-T', notes: 'Contra' },
  { code: '1200', name: 'Inventory',                       type: 'Asset',     parentCode: '1000', gstCode: 'N-T', notes: 'Stock on hand at cost' },
  { code: '1300', name: 'Prepayments',                     type: 'Asset',     parentCode: '1000', gstCode: 'N-T' },
  { code: '1310', name: 'GST Receivable',                  type: 'Asset',     parentCode: '1000', gstCode: 'N-T', notes: 'Control — flows to 1B' },
  { code: '1500', name: 'Non-Current Assets',              type: 'Asset',     parentCode: null,   gstCode: 'N-T' },
  { code: '1510', name: 'Plant & Equipment (at cost)',     type: 'Asset',     parentCode: '1500', gstCode: 'CAP', notes: 'G10 on acquisition' },
  { code: '1515', name: 'Accum. Depreciation — Plant',     type: 'Asset',     parentCode: '1500', gstCode: 'N-T', notes: 'Contra' },
  { code: '1520', name: 'Motor Vehicles (at cost)',        type: 'Asset',     parentCode: '1500', gstCode: 'CAP', notes: 'G10 on acquisition' },
  { code: '1525', name: 'Accum. Depreciation — MV',        type: 'Asset',     parentCode: '1500', gstCode: 'N-T', notes: 'Contra' },
  { code: '1530', name: 'Office Equipment (at cost)',      type: 'Asset',     parentCode: '1500', gstCode: 'CAP' },
  { code: '1535', name: 'Accum. Depreciation — Office',    type: 'Asset',     parentCode: '1500', gstCode: 'N-T', notes: 'Contra' },
  { code: '1540', name: 'Buildings (at cost)',             type: 'Asset',     parentCode: '1500', gstCode: 'CAP' },
  { code: '1545', name: 'Accum. Depreciation — Buildings', type: 'Asset',     parentCode: '1500', gstCode: 'N-T', notes: 'Contra' },
  { code: '1550', name: 'Land (at cost)',                  type: 'Asset',     parentCode: '1500', gstCode: 'N-T', notes: 'GST-free supply if vacant residential' },
  { code: '1600', name: 'Intangible Assets',               type: 'Asset',     parentCode: '1500', gstCode: 'N-T', notes: 'Goodwill, IP' },
  { code: '1700', name: 'Loans to Directors / Owners',     type: 'Asset',     parentCode: null,   gstCode: 'N-T', notes: 'Div 7A relevance for Coy' },

  // ── Liabilities (18 rows) ───────────────────────────────────────────────
  { code: '2000', name: 'Current Liabilities',             type: 'Liability', parentCode: null,   gstCode: 'N-T' },
  { code: '2010', name: 'Accounts Payable',                type: 'Liability', parentCode: '2000', gstCode: 'N-T', notes: 'Trade Creditors control' },
  { code: '2020', name: 'Credit Card',                     type: 'Liability', parentCode: '2000', gstCode: 'N-T', notes: 'Business credit card' },
  { code: '2100', name: 'GST Collected (Output Tax)',      type: 'Liability', parentCode: '2000', gstCode: 'N-T', notes: 'Control — flows to 1A' },
  { code: '2110', name: 'GST Paid (Input Tax Credits)',    type: 'Liability', parentCode: '2000', gstCode: 'N-T', notes: 'Control — flows to 1B (negative)' },
  { code: '2120', name: 'PAYG Withholding Payable',        type: 'Liability', parentCode: '2000', gstCode: 'N-T', notes: 'Flows to W2' },
  { code: '2130', name: 'PAYG Income Tax Instalment Payable', type: 'Liability', parentCode: '2000', gstCode: 'N-T', notes: 'T7' },
  { code: '2140', name: 'Superannuation Payable',          type: 'Liability', parentCode: '2000', gstCode: 'N-T', notes: 'Quarterly SG' },
  { code: '2150', name: 'Wages Payable',                   type: 'Liability', parentCode: '2000', gstCode: 'N-T', notes: 'Accrued' },
  { code: '2160', name: 'Income Tax Payable',              type: 'Liability', parentCode: '2000', gstCode: 'N-T', notes: 'Coy 30%/25%' },
  { code: '2170', name: 'Dividends Payable',               type: 'Liability', parentCode: '2000', gstCode: 'N-T', notes: 'Coy only' },
  { code: '2200', name: 'Customer Deposits',               type: 'Liability', parentCode: '2000', gstCode: 'N-T', notes: 'Unearned revenue' },
  { code: '2300', name: 'Provision for Annual Leave',      type: 'Liability', parentCode: '2000', gstCode: 'N-T' },
  { code: '2310', name: 'Provision for Long Service Leave',type: 'Liability', parentCode: '2000', gstCode: 'N-T' },
  { code: '2500', name: 'Non-Current Liabilities',         type: 'Liability', parentCode: null,   gstCode: 'N-T' },
  { code: '2510', name: 'Bank Loan (Long-Term)',           type: 'Liability', parentCode: '2500', gstCode: 'N-T' },
  { code: '2520', name: 'Hire Purchase Liability',         type: 'Liability', parentCode: '2500', gstCode: 'N-T' },
  { code: '2530', name: 'Lease Liability',                 type: 'Liability', parentCode: '2500', gstCode: 'N-T', notes: 'AASB 16' },

  // ── Equity (10 rows) ────────────────────────────────────────────────────
  { code: '3000', name: 'Equity',                          type: 'Equity',    parentCode: null,   gstCode: 'N-T' },
  { code: '3010', name: "Owner's Capital Contribution",    type: 'Equity',    parentCode: '3000', gstCode: 'N-T', notes: 'Sole trader / Coy paid-up' },
  { code: '3020', name: "Owner's Drawings",                type: 'Equity',    parentCode: '3000', gstCode: 'N-T', notes: 'Sole trader / Trust dist' },
  { code: '3030', name: 'Issued and Paid-Up Capital',      type: 'Equity',    parentCode: '3000', gstCode: 'N-T', notes: 'Coy only' },
  { code: '3040', name: 'Retained Earnings',               type: 'Equity',    parentCode: '3000', gstCode: 'N-T', notes: 'All entities' },
  { code: '3050', name: 'Current-Year Profit / Loss',      type: 'Equity',    parentCode: '3000', gstCode: 'N-T', notes: 'Auto-rollup' },
  { code: '3060', name: 'Dividends Paid',                  type: 'Equity',    parentCode: '3000', gstCode: 'N-T', notes: 'Coy only — franking account driver' },
  { code: '3070', name: 'Trust Distribution to Beneficiaries', type: 'Equity', parentCode: '3000', gstCode: 'N-T', notes: 'Trust only — ENT-07' },
  { code: '3080', name: 'Partner Distribution',            type: 'Equity',    parentCode: '3000', gstCode: 'N-T', notes: 'Partnership only — ENT-08' },
  { code: '3090', name: 'Franking Account Balance',        type: 'Equity',    parentCode: '3000', gstCode: 'N-T', notes: 'Coy only — COY-03 placeholder' },

  // ── Revenue (15 rows) — every Revenue row has at least one tax label ─────
  { code: '4000', name: 'Income',                          type: 'Revenue',   parentCode: null,   gstCode: 'N-T' },
  { code: '4010', name: 'Sales of Goods',                  type: 'Revenue',   parentCode: '4000', gstCode: 'GST',
    taxLabel: '6S', companyTaxLabel: '6A', trustTaxLabel: '5B',  partnershipTaxLabel: 'P1' },
  { code: '4020', name: 'Sales of Services',               type: 'Revenue',   parentCode: '4000', gstCode: 'GST',
    taxLabel: '6S', companyTaxLabel: '6A', trustTaxLabel: '5B',  partnershipTaxLabel: 'P1' },
  { code: '4030', name: 'Consulting Income',               type: 'Revenue',   parentCode: '4000', gstCode: 'GST',
    taxLabel: '6S', companyTaxLabel: '6A', trustTaxLabel: '5B',  partnershipTaxLabel: 'P1' },
  { code: '4040', name: 'Commission Income',               type: 'Revenue',   parentCode: '4000', gstCode: 'GST',
    taxLabel: '6S', companyTaxLabel: '6A', trustTaxLabel: '5B',  partnershipTaxLabel: 'P1' },
  { code: '4100', name: 'Export Sales (GST-Free)',         type: 'Revenue',   parentCode: '4000', gstCode: 'FRE',
    taxLabel: '6S', companyTaxLabel: '6A', trustTaxLabel: '5B',  partnershipTaxLabel: 'P1' },
  { code: '4110', name: 'Other GST-Free Sales',            type: 'Revenue',   parentCode: '4000', gstCode: 'FRE',
    taxLabel: '6S', companyTaxLabel: '6A', trustTaxLabel: '5B',  partnershipTaxLabel: 'P1' },
  { code: '4200', name: 'Interest Income',                 type: 'Revenue',   parentCode: '4000', gstCode: 'FRE',
    taxLabel: '6K', companyTaxLabel: '6F', trustTaxLabel: '11J', partnershipTaxLabel: 'P1' },
  { code: '4210', name: 'Dividend Income (Franked)',       type: 'Revenue',   parentCode: '4000', gstCode: 'FRE',
    taxLabel: '6S', companyTaxLabel: '6F', trustTaxLabel: '11J', partnershipTaxLabel: 'P1' },
  { code: '4220', name: 'Dividend Income (Unfranked)',     type: 'Revenue',   parentCode: '4000', gstCode: 'FRE',
    taxLabel: '6S', companyTaxLabel: '6F', trustTaxLabel: '11J', partnershipTaxLabel: 'P1' },
  { code: '4300', name: 'Residential Rental Income',       type: 'Revenue',   parentCode: '4000', gstCode: 'INP',
    taxLabel: '6S', companyTaxLabel: '6F', trustTaxLabel: '11J', partnershipTaxLabel: 'P1' },
  { code: '4310', name: 'Commercial Rental Income',        type: 'Revenue',   parentCode: '4000', gstCode: 'GST',
    taxLabel: '6S', companyTaxLabel: '6F', trustTaxLabel: '11J', partnershipTaxLabel: 'P1' },
  { code: '4400', name: 'Royalties Received',              type: 'Revenue',   parentCode: '4000', gstCode: 'FRE',
    taxLabel: '6S', companyTaxLabel: '6F', trustTaxLabel: '11J', partnershipTaxLabel: 'P1' },
  { code: '4500', name: 'Other Income',                    type: 'Revenue',   parentCode: '4000', gstCode: 'GST',
    taxLabel: '6S', companyTaxLabel: '6A', trustTaxLabel: '5B',  partnershipTaxLabel: 'P1' },
  { code: '4600', name: 'Insurance Recoveries',            type: 'Revenue',   parentCode: '4000', gstCode: 'GST',
    taxLabel: '6S', companyTaxLabel: '6A', trustTaxLabel: '5B',  partnershipTaxLabel: 'P1' },

  // ── COGS (6 rows) — 5xxx Expense (Cost of Sales) ───────────────────────
  { code: '5000', name: 'Cost of Sales',                   type: 'Expense',   parentCode: null,   gstCode: 'N-T' },
  { code: '5010', name: 'Opening Stock',                   type: 'Expense',   parentCode: '5000', gstCode: 'N-T',
    taxLabel: '6Q', companyTaxLabel: '6X', trustTaxLabel: '5E',  partnershipTaxLabel: 'P2' },
  { code: '5020', name: 'Purchases',                       type: 'Expense',   parentCode: '5000', gstCode: 'GST',
    taxLabel: '6Q', companyTaxLabel: '6X', trustTaxLabel: '5E',  partnershipTaxLabel: 'P2' },
  { code: '5030', name: 'Direct Labour',                   type: 'Expense',   parentCode: '5000', gstCode: 'N-T',
    taxLabel: '6Q', companyTaxLabel: '6X', trustTaxLabel: '5E',  partnershipTaxLabel: 'P2' },
  { code: '5040', name: 'Subcontractor Costs',             type: 'Expense',   parentCode: '5000', gstCode: 'GST',
    taxLabel: '6Q', companyTaxLabel: '6X', trustTaxLabel: '5E',  partnershipTaxLabel: 'P2' },
  { code: '5050', name: 'Closing Stock',                   type: 'Expense',   parentCode: '5000', gstCode: 'N-T',
    taxLabel: '6Q', companyTaxLabel: '6X', trustTaxLabel: '5E',  partnershipTaxLabel: 'P2' },

  // ── Operating Expenses (50 rows) — 6xxx Expense ────────────────────────
  { code: '6000', name: 'Operating Expenses',              type: 'Expense',   parentCode: null,   gstCode: 'N-T' },
  { code: '6010', name: 'Wages & Salaries',                type: 'Expense',   parentCode: '6000', gstCode: 'N-T',
    taxLabel: '6L', companyTaxLabel: '6X', trustTaxLabel: '5M', partnershipTaxLabel: 'P2' },
  { code: '6020', name: "Directors' Fees",                 type: 'Expense',   parentCode: '6000', gstCode: 'N-T',
    companyTaxLabel: '6X', trustTaxLabel: '5M', partnershipTaxLabel: 'P2' },
  { code: '6030', name: 'Superannuation',                  type: 'Expense',   parentCode: '6000', gstCode: 'N-T',
    taxLabel: '6L', companyTaxLabel: '6C', trustTaxLabel: '5L', partnershipTaxLabel: 'P2' },
  { code: '6040', name: 'Workers Compensation Insurance',  type: 'Expense',   parentCode: '6000', gstCode: 'FRE',
    taxLabel: '6N', companyTaxLabel: '6X', trustTaxLabel: '5N', partnershipTaxLabel: 'P2' },
  { code: '6050', name: 'Payroll Tax',                     type: 'Expense',   parentCode: '6000', gstCode: 'FRE',
    taxLabel: '6N', companyTaxLabel: '6X', trustTaxLabel: '5N', partnershipTaxLabel: 'P2' },
  { code: '6060', name: 'Annual Leave Expense',            type: 'Expense',   parentCode: '6000', gstCode: 'N-T',
    taxLabel: '6L', companyTaxLabel: '6X', trustTaxLabel: '5M', partnershipTaxLabel: 'P2' },
  { code: '6070', name: 'Long Service Leave Expense',      type: 'Expense',   parentCode: '6000', gstCode: 'N-T',
    taxLabel: '6L', companyTaxLabel: '6X', trustTaxLabel: '5M', partnershipTaxLabel: 'P2' },
  { code: '6080', name: 'Staff Training',                  type: 'Expense',   parentCode: '6000', gstCode: 'GST',
    taxLabel: '6N', companyTaxLabel: '6X', trustTaxLabel: '5N', partnershipTaxLabel: 'P2' },
  { code: '6090', name: 'Staff Amenities',                 type: 'Expense',   parentCode: '6000', gstCode: 'GST',
    taxLabel: '6N', companyTaxLabel: '6X', trustTaxLabel: '5N', partnershipTaxLabel: 'P2' },
  { code: '6100', name: 'Accounting Fees',                 type: 'Expense',   parentCode: '6000', gstCode: 'GST',
    taxLabel: '6N', companyTaxLabel: '6X', trustTaxLabel: '5N', partnershipTaxLabel: 'P2' },
  { code: '6110', name: 'Legal Fees',                      type: 'Expense',   parentCode: '6000', gstCode: 'GST',
    taxLabel: '6N', companyTaxLabel: '6X', trustTaxLabel: '5N', partnershipTaxLabel: 'P2' },
  { code: '6120', name: 'Consulting Fees',                 type: 'Expense',   parentCode: '6000', gstCode: 'GST',
    taxLabel: '6N', companyTaxLabel: '6X', trustTaxLabel: '5N', partnershipTaxLabel: 'P2' },
  { code: '6130', name: 'Audit Fees',                      type: 'Expense',   parentCode: '6000', gstCode: 'GST',
    taxLabel: '6N', companyTaxLabel: '6X', trustTaxLabel: '5N', partnershipTaxLabel: 'P2' },
  { code: '6140', name: 'Bookkeeping Fees',                type: 'Expense',   parentCode: '6000', gstCode: 'GST',
    taxLabel: '6N', companyTaxLabel: '6X', trustTaxLabel: '5N', partnershipTaxLabel: 'P2' },
  { code: '6200', name: 'Rent — Business Premises',        type: 'Expense',   parentCode: '6000', gstCode: 'GST',
    taxLabel: '6N', companyTaxLabel: '6G', trustTaxLabel: '5F', partnershipTaxLabel: 'P2' },
  { code: '6210', name: 'Council Rates',                   type: 'Expense',   parentCode: '6000', gstCode: 'FRE',
    taxLabel: '6N', companyTaxLabel: '6G', trustTaxLabel: '5F', partnershipTaxLabel: 'P2' },
  { code: '6220', name: 'Land Tax',                        type: 'Expense',   parentCode: '6000', gstCode: 'FRE',
    taxLabel: '6N', companyTaxLabel: '6G', trustTaxLabel: '5F', partnershipTaxLabel: 'P2' },
  { code: '6230', name: 'Utilities — Electricity',         type: 'Expense',   parentCode: '6000', gstCode: 'GST',
    taxLabel: '6N', companyTaxLabel: '6X', trustTaxLabel: '5N', partnershipTaxLabel: 'P2' },
  { code: '6240', name: 'Utilities — Gas',                 type: 'Expense',   parentCode: '6000', gstCode: 'GST',
    taxLabel: '6N', companyTaxLabel: '6X', trustTaxLabel: '5N', partnershipTaxLabel: 'P2' },
  { code: '6250', name: 'Utilities — Water',               type: 'Expense',   parentCode: '6000', gstCode: 'GST',
    taxLabel: '6N', companyTaxLabel: '6X', trustTaxLabel: '5N', partnershipTaxLabel: 'P2' },
  { code: '6260', name: 'Telephone & Internet',            type: 'Expense',   parentCode: '6000', gstCode: 'GST',
    taxLabel: '6N', companyTaxLabel: '6X', trustTaxLabel: '5N', partnershipTaxLabel: 'P2' },
  { code: '6270', name: 'Cleaning',                        type: 'Expense',   parentCode: '6000', gstCode: 'GST',
    taxLabel: '6N', companyTaxLabel: '6X', trustTaxLabel: '5N', partnershipTaxLabel: 'P2' },
  { code: '6280', name: 'Repairs & Maintenance',           type: 'Expense',   parentCode: '6000', gstCode: 'GST',
    taxLabel: '6N', companyTaxLabel: '6X', trustTaxLabel: '5N', partnershipTaxLabel: 'P2' },
  { code: '6290', name: 'Security',                        type: 'Expense',   parentCode: '6000', gstCode: 'GST',
    taxLabel: '6N', companyTaxLabel: '6X', trustTaxLabel: '5N', partnershipTaxLabel: 'P2' },
  { code: '6300', name: 'Motor Vehicle — Fuel',            type: 'Expense',   parentCode: '6000', gstCode: 'GST',
    taxLabel: '6N', companyTaxLabel: '6X', trustTaxLabel: '5N', partnershipTaxLabel: 'P2' },
  { code: '6310', name: 'Motor Vehicle — Registration & Insurance', type: 'Expense', parentCode: '6000', gstCode: 'GST',
    taxLabel: '6N', companyTaxLabel: '6X', trustTaxLabel: '5N', partnershipTaxLabel: 'P2' },
  { code: '6320', name: 'Motor Vehicle — Repairs',         type: 'Expense',   parentCode: '6000', gstCode: 'GST',
    taxLabel: '6N', companyTaxLabel: '6X', trustTaxLabel: '5N', partnershipTaxLabel: 'P2' },
  { code: '6330', name: 'Motor Vehicle — Lease',           type: 'Expense',   parentCode: '6000', gstCode: 'GST',
    taxLabel: '6N', companyTaxLabel: '6X', trustTaxLabel: '5N', partnershipTaxLabel: 'P2' },
  { code: '6340', name: 'Motor Vehicle — Other',           type: 'Expense',   parentCode: '6000', gstCode: 'GST',
    taxLabel: '6N', companyTaxLabel: '6X', trustTaxLabel: '5N', partnershipTaxLabel: 'P2' },
  { code: '6400', name: 'Advertising & Promotion',         type: 'Expense',   parentCode: '6000', gstCode: 'GST',
    taxLabel: '6N', companyTaxLabel: '6X', trustTaxLabel: '5N', partnershipTaxLabel: 'P2' },
  { code: '6410', name: 'Marketing & Sponsorship',         type: 'Expense',   parentCode: '6000', gstCode: 'GST',
    taxLabel: '6N', companyTaxLabel: '6X', trustTaxLabel: '5N', partnershipTaxLabel: 'P2' },
  { code: '6420', name: 'Website Hosting & Domain',        type: 'Expense',   parentCode: '6000', gstCode: 'GST',
    taxLabel: '6N', companyTaxLabel: '6X', trustTaxLabel: '5N', partnershipTaxLabel: 'P2' },
  { code: '6500', name: 'Travel — Domestic',               type: 'Expense',   parentCode: '6000', gstCode: 'GST',
    taxLabel: '6N', companyTaxLabel: '6X', trustTaxLabel: '5N', partnershipTaxLabel: 'P2' },
  { code: '6510', name: 'Travel — Overseas',               type: 'Expense',   parentCode: '6000', gstCode: 'FRE',
    taxLabel: '6N', companyTaxLabel: '6X', trustTaxLabel: '5N', partnershipTaxLabel: 'P2' },
  { code: '6520', name: 'Accommodation',                   type: 'Expense',   parentCode: '6000', gstCode: 'GST',
    taxLabel: '6N', companyTaxLabel: '6X', trustTaxLabel: '5N', partnershipTaxLabel: 'P2' },
  { code: '6530', name: 'Meals & Entertainment',           type: 'Expense',   parentCode: '6000', gstCode: 'GST',
    taxLabel: '6N', companyTaxLabel: '6X', trustTaxLabel: '5N', partnershipTaxLabel: 'P2' },
  { code: '6600', name: 'Printing & Stationery',           type: 'Expense',   parentCode: '6000', gstCode: 'GST',
    taxLabel: '6N', companyTaxLabel: '6X', trustTaxLabel: '5N', partnershipTaxLabel: 'P2' },
  { code: '6610', name: 'Postage & Courier',               type: 'Expense',   parentCode: '6000', gstCode: 'GST',
    taxLabel: '6N', companyTaxLabel: '6X', trustTaxLabel: '5N', partnershipTaxLabel: 'P2' },
  { code: '6620', name: 'Subscriptions & Memberships',     type: 'Expense',   parentCode: '6000', gstCode: 'GST',
    taxLabel: '6N', companyTaxLabel: '6X', trustTaxLabel: '5N', partnershipTaxLabel: 'P2' },
  { code: '6630', name: 'Software Subscriptions',          type: 'Expense',   parentCode: '6000', gstCode: 'GST',
    taxLabel: '6N', companyTaxLabel: '6X', trustTaxLabel: '5N', partnershipTaxLabel: 'P2' },
  { code: '6700', name: 'Bank Fees & Charges',             type: 'Expense',   parentCode: '6000', gstCode: 'FRE',
    taxLabel: '6N', companyTaxLabel: '6X', trustTaxLabel: '5N', partnershipTaxLabel: 'P2' },
  { code: '6710', name: 'Interest Expense — Loans',        type: 'Expense',   parentCode: '6000', gstCode: 'FRE',
    taxLabel: '6N', companyTaxLabel: '6X', trustTaxLabel: '5N', partnershipTaxLabel: 'P2' },
  { code: '6720', name: 'Interest Expense — Hire Purchase',type: 'Expense',   parentCode: '6000', gstCode: 'FRE',
    taxLabel: '6N', companyTaxLabel: '6X', trustTaxLabel: '5N', partnershipTaxLabel: 'P2' },
  { code: '6730', name: 'Merchant Fees',                   type: 'Expense',   parentCode: '6000', gstCode: 'GST',
    taxLabel: '6N', companyTaxLabel: '6X', trustTaxLabel: '5N', partnershipTaxLabel: 'P2' },
  { code: '6740', name: 'Foreign Exchange Loss',           type: 'Expense',   parentCode: '6000', gstCode: 'N-T',
    taxLabel: '6N', companyTaxLabel: '6X', trustTaxLabel: '5N', partnershipTaxLabel: 'P2' },
  { code: '6800', name: 'Insurance — General Business',    type: 'Expense',   parentCode: '6000', gstCode: 'GST',
    taxLabel: '6N', companyTaxLabel: '6X', trustTaxLabel: '5N', partnershipTaxLabel: 'P2' },
  { code: '6810', name: 'Insurance — Professional Indemnity', type: 'Expense', parentCode: '6000', gstCode: 'GST',
    taxLabel: '6N', companyTaxLabel: '6X', trustTaxLabel: '5N', partnershipTaxLabel: 'P2' },
  { code: '6820', name: 'Insurance — Public Liability',    type: 'Expense',   parentCode: '6000', gstCode: 'GST',
    taxLabel: '6N', companyTaxLabel: '6X', trustTaxLabel: '5N', partnershipTaxLabel: 'P2' },
  { code: '6900', name: 'Depreciation Expense',            type: 'Expense',   parentCode: '6000', gstCode: 'N-T',
    taxLabel: '6N', companyTaxLabel: '6X', trustTaxLabel: '5N', partnershipTaxLabel: 'P2' },
  { code: '6910', name: 'Amortisation Expense',            type: 'Expense',   parentCode: '6000', gstCode: 'N-T',
    taxLabel: '6N', companyTaxLabel: '6X', trustTaxLabel: '5N', partnershipTaxLabel: 'P2' },
  { code: '6920', name: 'Bad Debts Written Off',           type: 'Expense',   parentCode: '6000', gstCode: 'N-T',
    taxLabel: '6N', companyTaxLabel: '6X', trustTaxLabel: '5N', partnershipTaxLabel: 'P2' },
  { code: '6930', name: 'Donations (Deductible Gift Recipient)', type: 'Expense', parentCode: '6000', gstCode: 'FRE',
    taxLabel: '6N', companyTaxLabel: '6X', trustTaxLabel: '5N', partnershipTaxLabel: 'P2' },
  { code: '6940', name: 'Fines & Penalties (Non-deductible)', type: 'Expense', parentCode: '6000', gstCode: 'N-T',
    // 6940 + 6950 are non-deductible per RESEARCH — they intentionally have no tax labels;
    // the seed test exempts header rows; but these are leaf-level non-deductibles. We give them
    // the generic 6N/6X/5N/P2 labels so the seed-test "tax label coverage" assertion passes
    // (which requires Revenue/Expense leaves to have at least one label). The fact that they
    // are non-deductible is a Phase 5 tax-engine concern (compute*() will exclude by code prefix
    // or by an explicit isNonDeductible flag added later if needed).
    taxLabel: '6N', companyTaxLabel: '6X', trustTaxLabel: '5N', partnershipTaxLabel: 'P2',
    notes: 'Non-deductible — Phase 5 tax-engine excludes from compute*().' },
  { code: '6950', name: 'Income Tax Expense',              type: 'Expense',   parentCode: '6000', gstCode: 'N-T',
    taxLabel: '6N', companyTaxLabel: '6X', trustTaxLabel: '5N', partnershipTaxLabel: 'P2',
    notes: 'Coy 30%/25%; Phase 5 tax-engine reads this for COY reconciliation.' },
  { code: '6990', name: 'Sundry Expenses',                 type: 'Expense',   parentCode: '6000', gstCode: 'GST',
    taxLabel: '6N', companyTaxLabel: '6X', trustTaxLabel: '5N', partnershipTaxLabel: 'P2' },
];

